### ISSUE TITLE
Undesirable white background behind the FAB

### ISSUE THREAD

**Issue by praina** [JoaquimLey/faboptions#30] opened 2017-03-03 15:27 UTC
First of all, thank you for this library it is a great one. 

Now on to the bug.
There is an unnecessary white background coming behind the FAB and it is also blocking the background of the buttons.

## Expected result

I expected the FAB with a group of buttons as shown in the gif, I am getting the buttons but I am also getting undesirable white background which is obstructing the other view.

https://cloud.githubusercontent.com/assets/16051008/23556763/b5264b74-0053-11e7-9d6c-7101192b0a3f.png

**Comment by JoaquimLey** [comment] 2017-03-05 12:36
Can you confirm this only happens in >=N?

Possible duplicate of #29

**Comment by praina** [comment] 2017-03-05 13:42
I am using Marshmallow in my mobile device so it has to be a case for <N as well. No idea how it will work on pre-Marshmallow devices.

**Comment by JoaquimLey** [comment] 2017-03-09 16:16
Well, I'm not able to reproduce this... I've tinted my sample app with a black background and everything looks fine.

![screenshot_1489076102](https://cloud.githubusercontent.com/assets/6922748/23759101/b10b83b2-04e3-11e7-96d9-306adfcdf69b.png)

![screenshot_1489076168](https://cloud.githubusercontent.com/assets/6922748/23759110/b9462898-04e3-11e7-9939-714d65732e16.png)

**Comment by JoaquimLey** [comment] 2017-03-09 16:17
You should investigate you XML, re-open this issue if required.

**Closed by JoaquimLey** 2017-03-09 16:17 UTC
Labels: bug, duplicate
